version: '3'
services:
  php:
    build: docker/php8.1/Dockerfile .
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./docker/php8.1/Dockerfile:/var/www/html
    links:
      -db
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example